### ISSUE TITLE
Trouble Getting Pop-Up Windows to Work With Loop in JS

### ISSUE THREAD

**Issue by vaprdev** [davidwoodsandersen/PizzaQuest#1]
User Story: As a user, I want to be able to click on a google maps marker and see a window pop up with that marker's name and location. 

Error Message: There is no particular error message that I'm getting, more that it just does not function the way that I want it to. 

Description: I am attempting to create pop up windows on google maps that will allow the user to click a marker and see a restaurants name and rating. So far I am able to click on a marker and get a pop up window of the information, but the problem is that all of the markers are popping up in the same place. I've attempted to set the location manually and attach the window to the marker, but when I do so it still keeps popping up in the same location as the last created object.

**Comment by rapala61** [comment]
in person
